---
name: FlashSpace

options:
  createIntermediateGroups: true
  indentWidth: 4
  tabWidth: 4
  groupSortPosition: top
  bundleIdPrefix: pl.wojciechkulik

packages:
  ShortcutRecorder:
    github: Kentzo/ShortcutRecorder
    from: 3.4.0
  SymbolPicker:
    github: xnth97/SymbolPicker
    from: 1.6.0
  TOMLKit:
    github: LebJe/TOMLKit
    from: 0.6.0
  Yams:
    github: jpsim/Yams
    from: 5.2.0

targets:
  FlashSpace:
    type: application
    platform: macOS
    deploymentTarget: "14.0"
    sources: [FlashSpace]
    settings:
      base:
        MARKETING_VERSION: 1.4.22
        CURRENT_PROJECT_VERSION: 22
        CODE_SIGN_ENTITLEMENTS: FlashSpace/FlashSpace.entitlements
        DEVELOPMENT_TEAM: "${XCODE_DEVELOPMENT_TEAM}"
        ENABLE_HARDENED_RUNTIME: true
        DEAD_CODE_STRIPPING: true
        ENABLE_USER_SCRIPT_SANDBOXING: false
        ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: YES
        GENERATE_INFOPLIST_FILE: true
        INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.productivity
        INFOPLIST_KEY_LSUIElement: true
        INFOPLIST_KEY_CFBundleDisplayName: FlashSpace
        INFOPLIST_KEY_NSHumanReadableCopyright: © 2025 Wojciech Kulik. All rights reserved.
      configs:
        debug:
          INFOPLIST_KEY_CFBundleDisplayName: FlashSpace Dev
          PRODUCT_NAME: FlashSpace-Dev
          PRODUCT_BUNDLE_IDENTIFIER: pl.wojciechkulik.FlashSpace.dev

    dependencies:
      - sdk: ServiceManagement.framework
      - package: ShortcutRecorder
      - package: SymbolPicker
      - package: TOMLKit
      - package: Yams

    preBuildScripts:
      - name: Run SwiftLint
        script: |
          if [ "$GITHUB_ACTIONS" != "true" ]; then
            /opt/homebrew/bin/swiftlint --use-alternative-excluding
          fi
        basedOnDependencyAnalysis: false
        showEnvVars: false
      - name: Run SwiftFormat
        script: |
          if [ "$GITHUB_ACTIONS" != "true" ]; then
            /opt/homebrew/bin/swiftformat --lint ${SRCROOT} --config .swiftformat || exit 0
          fi
        basedOnDependencyAnalysis: false
        showEnvVars: false
