# https://docs.github.com/en/actions/use-cases-and-examples/building-and-testing/building-and-testing-swift
# https://github.com/swift-actions/setup-swift

name: ci

on: [push, pull_request]

jobs:
  build:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        swift: ["5.10", "6.0"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: ${{ matrix.swift }}
      - run: sw_vers && swift --version
      - uses: actions/checkout@v4
      - run: swift run swiftlint --reporter github-actions-logging --strict
      - run: |
          brew install swiftformat
          swiftformat .
      - run: swift build || true  # No Package.swift file.
      - run: swift test || true  # No Package.swift file.
